### ISSUE TITLE
Ko dodajam zaposlenega v brskalniku ne dela

### ISSUE THREAD

**Issue by Petja-Murnik** [Petja-Murnik/OPB-projekt-UP#1]
ko poženem v brskalniku neki.py in pridem do strani /dodaj_zaposlenega in izpolnim obrazec, mi vrne naslednjo napako:
invalid input syntax for type numeric: "" LINE 4: VALUES('', '','','','','','','','' ) ^

**Comment by majbc1999** [comment]
Živjo,

sem malo pogledal projekt in našel nekaj težav, ki vodijo do napake.

Ko kličeš `request.forms`, ti vrne slovar, ki ima `name` inputa kot ključ. Torej, na primer, v primeru:
```html
<p>Ime: <input name="Ime" type="text" value="{{ime}}" class="form-control" required></p>
```
zaenkrat `ime = request.forms.ime` ne naredi nič. Delovalo bi `ime = request.forms.get('Ime')` (velika začetnica). Podobno boste morali popraviti za vse parametre. V htmlju sicer manjka input za parameter `naslov`. Svetujem tudi, da ne uporabljate šumnikov v imenih inputov. Trenutno bo sicer treba za uporabniško ime klicati `uporabnisko_ime = request.forms.get('UporabniÅ¡ko ime')`.

Drugo napako sem opazil v `dodaj_zaposlenega.html`. Če želite, da bo projekt uspešno delal tudi na Binderju, je potrebno povsod v funkcijo `url` podati ime funkcije v `neki.py`, ne pa poti. Lokalno sicer projekt deluje, a svetujem konsistentnost, da ne bo na koncu težav z Binderjem.

Še ena težava, ki jo vidim: v datoteki `auth_public.py` ne bi smeli biti pravi podatki, ampak podatki za javnost. Podatke s svojim uporabniškim imenom in geslom ne smete imeti na repozitoriju (sicer jih lahko uporablja kdorkoli). Pravilen pristop je, da vsak pri sebi lokalno hrani datoteko `auth.py`, ki je dodana v `.gitignore`. Bolj podroben opis problema je tudi v tem [issueju](https://github.com/MasaOrelj/Svecano-prisegam-da-imam-nekaj-za-bregom/issues/2). @Petja-Murnik, ko popraviš, prosim še spremeni geslo za bazo.
